[package]
name = "remotefs"
version = "0.3.1"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs"
edition = "2024"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = [
  "scp-client",
  "sftp-client",
  "ftp-client",
  "s3-client",
  "kube-client",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs"
rust-version = "1.89.0"
description = "a client library to work with all file transfer protocols"

[features]
async = ["dep:async-trait", "dep:futures-io"]
default = ["find"]
# misc
find = ["dep:wildmatch"]
no-log = ["log/max_level_off"]
tokio = ["async", "dep:tokio", "dep:tokio-util"]

[dependencies]
async-trait = { version = "0.1", optional = true }
futures-io = { version = "0.3", optional = true }
log = "0.4"
thiserror = "2"
tokio = { version = "1", default-features = false, features = ["io-util", "rt", "sync"], optional = true }
tokio-util = { version = "0.7", default-features = false, features = ["compat", "io-util"], optional = true }
wildmatch = { version = "2", optional = true }

[dev-dependencies]
env_logger = "0.11"
pretty_assertions = "1"
tempfile = "3"
